### PR TITLE
Fix OwnerRefInvalidNamespace warning for RoleBindings

### PR DESCRIPTION
**Pull request by vigohe**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | no
| License         | Apache 2.0

### What's in this PR?

Fix OwnerRefInvalidNamespace warning when RoleBindings are referring to a Service Account that doesn't exists in the same namespace

### Why?
From Kubernetes >= 1.20 `ownerReferences` section will add the attribute `blockOwnerDeletion` to `false` as default. So when you have a warning about  `OwnerRefInvalidNamespace` the garbage collector will delete the resource, in this case the `RoleBinding` because the Service Account it's declared at another namespace.

### Additional context

```
In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. You can check for that kind of Event by running kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace.
```

ref: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by pbalogh-sa** [comment]
Thanks @vigohe for your contribution! There is a CI failure, I updated the GH kind action and it solved the issue. Please rebase to the master and the CI failure will be disappeared. Otherwise LGTM.

**Comment by vigohe** [comment]
@pbalogh-sa thanks!

**Review by pbalogh-sa — APPROVED** [review]
Thanks!

**Review by pbalogh-sa — CHANGES_REQUESTED** [review]
There are some conflicts. I don't know why. I will check it.

**Review by pbalogh-sa — APPROVED** [review]

**Comment by pbalogh-sa** [comment]
I fixed the merge conflict issues and created a new PR: #80

**Pull request closed without merging**
