### PR TITLE
ensure that pods are redeployed upon configmap change

### LINKED ISSUE #39: Changing log level and applying it with helm does not take an effect
**Describe the bug**
Changing log level and applying it with helm does not take an effect.

**Steps to reproduce the issue:**
1. In values.yaml change log.level to debug
1. helm upgrade --install
1. observe that ConfigMap has changed but application still does not print debug level messages.

**Expected behaviour**
Application changes it log level

### PR DESCRIPTION
**Pull request by j-zimnowoda**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #39
| License         | Apache 2.0

### Checklist
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by pbalogh-sa** [comment]
Thanks @j-zimnowoda ! Please bump the chart version.

**Comment by j-zimnowoda** [comment]
> Thanks @j-zimnowoda ! Please bump the chart version. Otherwise LGTM.
> 
> https://github.com/banzaicloud/jwt-to-rbac/blob/0af1fd57961abdb58ce1bb2897411e43f057acab/charts/jwt-to-rbac/Chart.yaml#L5

Good point, thanks!

**Review by pbalogh-sa — APPROVED** [review]
Thanks!

**Comment by pbalogh-sa** [comment]
The chart version 0.3.1 has been released. @j-zimnowoda

**Pull request merged**
