### PR TITLE
Fix ClusterRole & ClusterRoleBinding hotreload

### LINKED ISSUE #91: Hot reload of `customGroups` not working
**Describe the bug**

When you change the ConfigMap `jwt-to-rbac` at the level of `customGroups` at runtime, this changes doesn't applied.

This is because this conditions will be always `nil` because `ClusterRole` or `ClusterRoleBinding` already exists.

https://github.com/banzaicloud/jwt-to-rbac/blob/bb2185da9317083c6ff92ca0a64c13f215cefeda/pkg/rbachandler/rbac_handler.go#L248-L250

https://github.com/banzaicloud/jwt-to-rbac/blob/bb2185da9317083c6ff92ca0a64c13f215cefeda/pkg/rbachandler/rbac_handler.go#L331-L333

**Steps to reproduce the issue:**
Change something at `customGroups` level

**Expected behavior**

When someone change something at `customGroups` the ClusterRole & ClusterRoleBinding changes should be reflected

### PR DESCRIPTION
**Pull request by vigohe**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #91 
| License         | Apache 2.0

### What's in this PR?

fixes #91 and deletes ClusterRoles when CustomGroup name is not present at the config 

### Why?

- Hot Reload is not working as intended
- When a CustomGroup it's deleted it should also delete the related ClusterRole and ClusterRoleBinding or RoleBinding

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)
- [x] User guide and development docs updated (if needed)
- [x] Related Helm chart(s) updated (if needed)

### CODE REVIEW

**Comment by pbalogh-sa** [comment]
@vigohe Thanks for contributions. I will check it soon.

**Comment by vigohe** [comment]
> @vigohe Thanks for contributions. I will check it soon.

Nice!

Do you know a better way to delete as cascade all resources related to a `ClusterRole`, because the only way I found, was to label each resource ( `ClusterRoleBinding` & `RoleBinding` ) with the label `crole`

**Comment by pbalogh-sa** [comment]
@vigohe  I think you can set the ownerreference of rolebindings to the proper role or clusterrole. In this case when you delete the clusterrole or role, the rolebindings will be deleted. This doesn't work in the case of clusterscope resources if the K8s version is 1.21 or above.

**Review by pbalogh-sa — APPROVED** [review]
@vigohe Using labels works in the case of cluster-scoped resources as well (for example clusterrolebindings). I think it's an universal solution . Thanks.
Please resolve conflicts otherwise LGTM.

**Review by pbalogh-sa — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by vigohe** [comment]
> Please resolve conflicts otherwise LGTM.



> Please resolve conflicts otherwise LGTM.

Did I fix it ?

**Review by pbalogh-sa — APPROVED** [review]

**Comment by pbalogh-sa** [comment]
@vigohe Some conflicts are found. Please resolve them.

**Comment by vigohe** [comment]
> @vigohe Some conflicts are found. Please resolve them.

Don't see any conflicts

**Comment by pbalogh-sa** [comment]
@vigohe . I can squash and merge instead of rebasing.

**Pull request merged**
